name: Reusable deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to deploy'
        required: false
        default: dist
        type: string
      deploy_env:
        description: 'Environment to deploy to'
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Show files
        run: ls -la
      - name: Output Info
        run: echo "Deploying & uploading..."

